### ISSUE TITLE
Paper link

### ISSUE THREAD

**Issue by dvcopae** [AleksandarMitrevski/se-requirements-classification#1]
Hello Aleksandar!

Apologies for writing here, but I didn't find any other suitable place. I would like to cite your work in my Bachelor's research paper, but unfortunately, I can't find any link for it outside of GitHub. Could you please help me with a link?

Regards,
Danut Copae.

**Comment by AleksandarMitrevski** [comment]
Hello Danut,

This project is not part of any research publication. Feel free to reproduce and publish. Otherwise, your citing options are limited to a GitHub repository.

Regards,
Aleksandar Mitrevski
